# Generated by Django 4.1.6 on 2023-02-18 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaapi', '0002_remove_book_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bibliotecaapi.user'),
            preserve_default=False,
        ),
    ]
